(()=>{"use strict";
const SOURCES=[
{source_id:"rules-hub",title:"Riftbound Rules Hub",authority:"official",kind:"discovery",version:"live",url:"https://playriftbound.com/en-us/rules-hub/",live:true},
{source_id:"core-rules-2026-07-16",title:"Core Rules",authority:"official",kind:"core_rules",version:"2026-07-16",url:"https://playriftbound.com/en-us/rules-hub/",live:true},
{source_id:"tournament-rules-2026-07-16",title:"Tournament Rules",authority:"official",kind:"tournament_rules",version:"2026-07-16",url:"https://playriftbound.com/en-us/rules-hub/",live:true},
{source_id:"vendetta-patch-notes-2026-07-17",title:"Vendetta Patch Notes",authority:"official",kind:"official_clarification",version:"2026-07-17",url:"https://playriftbound.com/en-us/news/announcements/core-rules-vendetta-patch-notes/",live:false},
{source_id:"vendetta-errata-2026-07-23",title:"Vendetta Errata",authority:"official",kind:"errata",version:"2026-07-23",url:"https://playriftbound.com/en-us/news/announcements/vendetta-errata-updates/",live:false},
{source_id:"riftjudge-community",title:"RiftJudge",authority:"community",kind:"community_rulings",version:"live",url:"https://app.riftjudge.com/",live:true}
];
const AXES={mechanics:["Current official FAQ / clarification","Latest Core Rules","Errata-applied card text"],procedure:["Event addendum","Tournament Rules","Core Rules where unmodified","Event Head Judge"]};
const CONSTANTS={schema_version:"rule-consultation.v1",mode:"rule-consult",official_status:"unofficial",state_effect:"none"};
let consultation=null,toastTimer=null;
const $=s=>document.querySelector(s),els={questionForm:$("#question-form"),factForm:$("#fact-form"),assumptionForm:$("#assumption-form"),sourceForm:$("#source-form"),answerForm:$("#answer-form"),sourceSelect:$("#source-select"),sourcePreview:$("#source-preview"),record:$("#record"),recordEmpty:$("#record-empty"),recordCount:$("#record-count"),copyBrief:$("#copy-brief"),export:$("#export"),reset:$("#reset"),toast:$("#toast"),status:$("#status"),result:$("#result")};
const now=()=>new Date().toISOString().replace(/\.\d{3}Z$/,"Z");
const id=()=>globalThis.crypto?.randomUUID?crypto.randomUUID():`rc-${Date.now()}-${Math.random().toString(16).slice(2)}`;
const values=form=>Object.fromEntries(new FormData(form).entries());
const esc=v=>String(v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
function toast(message){clearTimeout(toastTimer);els.toast.textContent=message;els.toast.classList.add("show");toastTimer=setTimeout(()=>els.toast.classList.remove("show"),2400)}
function locked(element,value){element.classList.toggle("locked",value);element.querySelectorAll("input,select,textarea,button").forEach(control=>control.disabled=value)}
function renderLadder(axis){$("#authority-ladder").innerHTML=AXES[axis].map((item,index)=>`<li><b>0${index+1}</b><strong>${esc(item)}</strong><span>${index===AXES[axis].length-1&&axis==="procedure"?"Final authority at the live event":"Apply only within its stated scope"}</span></li>`).join("");document.querySelectorAll("[data-axis]").forEach(button=>button.classList.toggle("active",button.dataset.axis===axis))}
function renderSourceOptions(){els.sourceSelect.innerHTML=SOURCES.map(source=>`<option value="${source.source_id}">${source.authority==="community"?"Community · ":"Official · "}${esc(source.title)} (${source.version})</option>`).join("");renderSourcePreview()}
function renderSourcePreview(){const source=SOURCES.find(item=>item.source_id===els.sourceSelect.value)||SOURCES[0];els.sourcePreview.innerHTML=`<strong>${esc(source.title)}</strong> · ${esc(source.kind.replaceAll("_"," "))} · ${source.live?"check live before use":"dated source"}${source.authority==="community"?" · supporting only":""}`}
function pendingStage(){if(!consultation)return"question";if(!consultation.facts.length)return"context";if(!consultation.sources.length)return"source";if(consultation.status!=="final")return"answer";return"complete"}
function setStatus(stage){const map={question:["1","Define the question","Start with the interaction and its rules context."],context:["2","Establish facts and assumptions","At least one confirmed fact is required."],source:["3","Attach the rule basis","Use an exact locator and current official source."],answer:["4","Analyze and calibrate","Finalize the answer, confidence, and escalation."],complete:["✓","Consultation finalized","Export the record or start another question."]};const [n,title,detail]=map[stage];els.status.querySelector("span").textContent=n;els.status.querySelector("strong").textContent=title;els.status.querySelector("p").textContent=detail}
function renderRecord(){if(!consultation){els.record.classList.remove("has-items");els.recordEmpty.hidden=false;els.recordCount.textContent="0 items";els.record.innerHTML="";return}const groups=[];if(consultation.facts.length)groups.push(["Facts",consultation.facts.map(item=>`<div class="record-item"><strong>${esc(item.text)}</strong><span>${esc(item.origin.replaceAll("_"," "))}</span></div>`).join("")]);if(consultation.assumptions.length)groups.push(["Assumptions",consultation.assumptions.map(item=>`<div class="record-item"><strong>${esc(item.text)}</strong><span>${item.material?"material":"non-material"}</span></div>`).join("")]);if(consultation.sources.length)groups.push(["Sources",consultation.sources.map(item=>{const source=SOURCES.find(s=>s.source_id===item.source_id);return`<div class="record-item"><strong>${esc(source?.title||item.source_id)}</strong><p>${esc(item.locator)}</p><span>${esc(source?.authority||"unknown")}</span></div>`}).join("")]);const count=consultation.facts.length+consultation.assumptions.length+consultation.sources.length;els.record.innerHTML=groups.map(([title,body])=>`<section class="record-group"><h3>${title}</h3>${body}</section>`).join("");els.record.classList.toggle("has-items",count>0);els.recordEmpty.hidden=count>0;els.recordCount.textContent=`${count} item${count===1?"":"s"}`}
function renderResult(){const answer=consultation?.answer;els.result.hidden=!answer;if(!answer)return;$("#result-confidence").textContent=`${answer.confidence} confidence${answer.conditional?" · conditional":""}`;$("#result-conclusion").textContent=answer.conclusion;$("#result-steps").innerHTML=answer.analysis_steps.map(step=>`<li>${esc(step)}</li>`).join("");$("#result-escalation").textContent=answer.escalation_required?`Escalate to ${answer.escalation_target.replaceAll("_"," ")}: ${answer.escalation_reason}`:"No escalation required on the supplied facts."}
function render(){const stage=pendingStage(),draft=consultation?.status==="draft";locked(els.questionForm,Boolean(consultation));locked($("#context-content"),!draft);locked(els.sourceForm,!draft);locked(els.answerForm,!draft||!consultation?.facts.length||!consultation?.sources.length);els.copyBrief.disabled=!draft||!consultation?.facts.length;els.export.disabled=!consultation;els.reset.disabled=!consultation;$("#question-status").textContent=consultation?"Complete":"Required";$("#context-status").textContent=!consultation?"Locked":consultation.facts.length?`${consultation.facts.length} facts`:"Required";$("#source-status").textContent=!consultation?"Locked":consultation.sources.length?`${consultation.sources.length} attached`:"Required";$("#answer-status").textContent=!consultation?"Locked":consultation.status==="final"?"Final":"Ready";$("#question-panel").open=!consultation;$("#context-panel").open=stage==="context";$("#source-panel").open=stage==="source";$("#answer-panel").open=stage==="answer";setStatus(stage);renderRecord();renderResult()}
document.querySelectorAll("[data-axis]").forEach(button=>button.addEventListener("click",()=>renderLadder(button.dataset.axis)));
els.sourceSelect.addEventListener("change",renderSourcePreview);
els.questionForm.addEventListener("submit",event=>{event.preventDefault();const v=values(event.currentTarget),required=[v.createdBy,v.question,v.format,v.ruleset].map(item=>item.trim());if(required.some(item=>!item)){toast("Question, format, ruleset, and operator cannot be blank.");return}consultation={...CONSTANTS,consultation_id:id(),created_at:now(),created_by:required[0],status:"draft",question_type:v.questionType,question:required[1],format:required[2],ruleset_as_of:required[3],facts:[],assumptions:[],sources:[],answer:null};render();toast("Draft consultation created. No ruling has been asserted.")});
els.factForm.addEventListener("submit",event=>{event.preventDefault();const v=values(event.currentTarget),text=v.text.trim();if(!text){toast("A confirmed fact cannot be blank.");return}consultation.facts.push({text,origin:v.origin});event.currentTarget.elements.text.value="";render();toast("Confirmed fact added.")});
els.assumptionForm.addEventListener("submit",event=>{event.preventDefault();const v=values(event.currentTarget),text=v.text.trim();if(!text){toast("An assumption cannot be blank.");return}consultation.assumptions.push({text,material:v.material==="on"});event.currentTarget.reset();render();toast("Assumption separated from confirmed facts.")});
els.sourceForm.addEventListener("submit",event=>{event.preventDefault();const v=values(event.currentTarget),locator=v.locator.trim();if(!locator){toast("Use an exact rule, section, heading, or card locator.");return}if(consultation.sources.some(item=>item.source_id===v.sourceId&&item.locator===locator)){toast("That source and locator are already attached.");return}consultation.sources.push({source_id:v.sourceId,locator,accessed_at:now()});event.currentTarget.elements.locator.value="";render();toast("Source locator attached.")});
els.answerForm.addEventListener("submit",event=>{event.preventDefault();const v=values(event.currentTarget),material=consultation.assumptions.some(item=>item.material),official=consultation.sources.some(item=>SOURCES.find(source=>source.source_id===item.source_id)?.authority==="official"),conclusion=v.conclusion.trim(),steps=v.steps.split("\n").map(line=>line.trim()).filter(Boolean),reason=v.confidenceReason.trim();if(!conclusion||!steps.length||!reason){toast("Conclusion, analysis steps, and confidence reason cannot be blank.");return}if(v.confidence==="High"&&material){toast("High confidence is blocked while a material assumption remains.");return}if(v.confidence==="High"&&!official){toast("High confidence requires an official source.");return}if(v.escalationTarget!=="none"&&!v.escalationReason.trim()){toast("Explain why escalation is required.");return}if(consultation.question_type==="source_conflict"&&v.confidence==="High"){toast("A source conflict cannot finalize at High confidence.");return}consultation.status="final";consultation.answer={conclusion,conditional:v.conditional==="on",analysis_steps:steps,confidence:v.confidence,confidence_reason:reason,escalation_required:v.escalationTarget!=="none",escalation_target:v.escalationTarget,escalation_reason:v.escalationReason.trim()};render();toast("Unofficial consultation finalized with no state effect.")});
els.copyBrief.addEventListener("click",async()=>{const brief=["Use the Riftbound rule-consult mode.",`Question type: ${consultation.question_type}`,`Question: ${consultation.question}`,`Format: ${consultation.format}`,`Ruleset as of: ${consultation.ruleset_as_of}`,"Facts:",...consultation.facts.map(item=>`- [${item.origin}] ${item.text}`),"Assumptions:",...(consultation.assumptions.length?consultation.assumptions.map(item=>`- [${item.material?"material":"non-material"}] ${item.text}`):["- none recorded"]),"Return the most likely answer, rule basis with exact locators, analysis steps, confidence and reason, and escalation. State that the result is unofficial and has no game-state effect."].join("\n");try{await navigator.clipboard.writeText(brief);toast("Research brief copied.")}catch{toast("Clipboard permission unavailable; copy the record manually.")}});
els.export.addEventListener("click",()=>{const blob=new Blob([`${JSON.stringify(consultation,null,2)}\n`],{type:"application/json"}),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=`rule-consult-${consultation.consultation_id.slice(0,8)}.json`;link.click();URL.revokeObjectURL(url);toast("Consultation JSON exported.")});
els.reset.addEventListener("click",()=>{if(!confirm("Reset this in-tab consultation? Export first if you need the record."))return;consultation=null;[els.questionForm,els.factForm,els.assumptionForm,els.sourceForm,els.answerForm].forEach(form=>form.reset());renderSourceOptions();render();toast("Consultation reset.")});
renderLadder("mechanics");renderSourceOptions();render();
})();
