(()=>{"use strict";
const SOURCES=[
{source_id:"rules-hub",title:"Riftbound Rules Hub",authority:"official",document_class:"rules_hub",locale:"en-US",region:"global",status:"active",version:"live",live:true},
{source_id:"core-rules-2026-07-16",title:"Core Rules",authority:"official",document_class:"core_rules",locale:"en-US",region:"global",status:"active",version:"2026-07-16",live:true},
{source_id:"tournament-rules-2026-07-16",title:"Tournament Rules",authority:"official",document_class:"tournament_rules",locale:"en-US",region:"global",status:"active",version:"2026-07-16",live:true},
{source_id:"vendetta-patch-notes-2026-07-17",title:"Vendetta Patch Notes",authority:"official",document_class:"patch_notes",locale:"en-US",region:"global",status:"active",version:"2026-07-17",live:false},
{source_id:"vendetta-errata-2026-07-23",title:"Vendetta Errata",authority:"official",document_class:"card_errata",locale:"en-US",region:"global",status:"active",version:"2026-07-23",live:false},
{source_id:"vendetta-rules-faq-2026-08-14",title:"Vendetta Rules FAQ",authority:"official",document_class:"official_faq",locale:"en-US",region:"global",status:"active",version:"2026-08-14",live:true},
{source_id:"unleashed-rules-faq-2026-04-29",title:"Unleashed Rules FAQ",authority:"official",document_class:"official_faq",locale:"en-US",region:"global",status:"active",version:"2026-04-29",live:true},
{source_id:"spiritforged-faq-2026-01-14",title:"Spiritforged FAQ",authority:"official",document_class:"official_faq",locale:"en-US",region:"global",status:"active",version:"2026-01-14",live:true},
{source_id:"origins-faq-2025-10-16",title:"Origins FAQ",authority:"official",document_class:"official_faq",locale:"en-US",region:"global",status:"active",version:"2025-10-16",live:true},
{source_id:"origins-errata-2025-10-28",title:"Origins Card Errata",authority:"official",document_class:"card_errata",locale:"en-US",region:"global",status:"active",version:"2025-10-28",live:false},
{source_id:"spiritforged-errata-2026-01-14",title:"Spiritforged Card Errata",authority:"official",document_class:"card_errata",locale:"en-US",region:"global",status:"active",version:"2026-01-14",live:false},
{source_id:"core-rules-zh-cn-2026-07-17",title:"《符文战场》核心规则",authority:"official",document_class:"core_rules",locale:"zh-CN",region:"CN",status:"active",version:"2026-07-17",live:true},
{source_id:"tournament-rules-zh-cn-2026-07-17",title:"《符文战场》赛事规则",authority:"official",document_class:"tournament_rules",locale:"zh-CN",region:"CN",status:"active",version:"2026-07-17",live:true},
{source_id:"ban-list-zh-cn-2026-07-17",title:"《符文战场》赛事禁限卡表",authority:"official",document_class:"ban_list",locale:"zh-CN",region:"CN",status:"active",version:"2026-07-17",live:true},
{source_id:"origins-errata-zh-cn-2025-10-28",title:"起源系列勘误汇总",authority:"official",document_class:"card_errata",locale:"zh-CN",region:"CN",status:"active",version:"2025-10-28",live:false},
{source_id:"origins-judge-faq-zh-cn-2025-10-24",title:"起源系列裁判 FAQ",authority:"judge_guidance",document_class:"judge_faq",locale:"zh-CN",region:"CN",status:"active",version:"2025-10-24",live:false},
{source_id:"spiritforged-errata-zh-cn-2026-01-14",title:"铸魂淬炼系列勘误汇总",authority:"official",document_class:"card_errata",locale:"zh-CN",region:"CN",status:"active",version:"2026-01-14",live:false},
{source_id:"spiritforged-official-faq-zh-cn-2026-01-14",title:"铸魂淬炼系列官方 FAQ",authority:"official",document_class:"official_faq",locale:"zh-CN",region:"CN",status:"active",version:"2026-01-14",live:false},
{source_id:"spiritforged-judge-faq-zh-cn-2026-01-14",title:"铸魂淬炼系列裁判 FAQ",authority:"judge_guidance",document_class:"judge_faq",locale:"zh-CN",region:"CN",status:"active",version:"2026-01-14",live:false},
{source_id:"unleashed-errata-zh-cn-2026-04-03",title:"破限系列勘误汇总",authority:"official",document_class:"card_errata",locale:"zh-CN",region:"CN",status:"active",version:"2026-04-03",live:false},
{source_id:"unleashed-official-faq-zh-cn-2026-04-30",title:"破限系列官方 FAQ",authority:"official",document_class:"official_faq",locale:"zh-CN",region:"CN",status:"active",version:"2026-04-30",live:false},
{source_id:"unleashed-judge-faq-zh-cn-2026-04-16",title:"破限系列裁判 FAQ (superseded)",authority:"judge_guidance",document_class:"judge_faq",locale:"zh-CN",region:"CN",status:"superseded",version:"2026-04-16",live:false},
{source_id:"unleashed-judge-faq-zh-cn-2026-05-11",title:"破限系列裁判 FAQ",authority:"judge_guidance",document_class:"judge_faq",locale:"zh-CN",region:"CN",status:"active",version:"2026-05-11",live:false},
{source_id:"riftjudge-community",title:"RiftJudge",authority:"community",document_class:"community_index",locale:"en-US",region:"global",status:"supporting",version:"live",live:true},
{source_id:"riftbound-faq-community",title:"Riftbound FAQ",authority:"community",document_class:"community_index",locale:"en-US",region:"global",status:"supporting",version:"live",live:true},
{source_id:"riftref-community",title:"RiftRef",authority:"community",document_class:"community_index",locale:"en-US",region:"global",status:"supporting",version:"live",live:true},
{source_id:"runejudge-discovery",title:"RuneJudge source library",authority:"community",document_class:"community_index",locale:"zh-CN",region:"CN",status:"supporting",version:"live",live:true}
];
// Demonstration checks, generated from the real engines by
// skill/scripts/build_engine_check_fixtures.py and loaded as a global because
// this page opens from disk and makes no network requests.
const ENGINE_CHECKS=(globalThis.window?.RC_ENGINE_CHECK_FIXTURES?.fixtures||[]);
const AXES={mechanics:["Current official FAQ / clarification","Latest Core Rules","Errata-applied card text"],procedure:["Event addendum","Tournament Rules","Core Rules where unmodified","Event Head Judge"]};
const CONSTANTS={schema_version:"rule-consultation.v1",mode:"rule-consult",official_status:"unofficial",state_effect:"none"};
let consultation=null,toastTimer=null;
const $=s=>document.querySelector(s),els={questionForm:$("#question-form"),factForm:$("#fact-form"),assumptionForm:$("#assumption-form"),sourceForm:$("#source-form"),answerForm:$("#answer-form"),sourceSelect:$("#source-select"),sourcePreview:$("#source-preview"),engineForm:$("#engine-form"),engineSelect:$("#engine-select"),engineView:$("#engine-check-view"),engineCount:$("#engine-count"),record:$("#record"),recordEmpty:$("#record-empty"),recordCount:$("#record-count"),copyBrief:$("#copy-brief"),export:$("#export"),reset:$("#reset"),toast:$("#toast"),status:$("#status"),result:$("#result")};
const now=()=>new Date().toISOString().replace(/\.\d{3}Z$/,"Z");
const id=()=>globalThis.crypto?.randomUUID?crypto.randomUUID():`rc-${Date.now()}-${Math.random().toString(16).slice(2)}`;
const values=form=>Object.fromEntries(new FormData(form).entries());
const esc=v=>String(v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
function toast(message){clearTimeout(toastTimer);els.toast.textContent=message;els.toast.classList.add("show");toastTimer=setTimeout(()=>els.toast.classList.remove("show"),2400)}
function locked(element,value){element.classList.toggle("locked",value);element.querySelectorAll("input,select,textarea,button").forEach(control=>control.disabled=value)}
function renderLadder(axis){$("#authority-ladder").innerHTML=AXES[axis].map((item,index)=>`<li><b>0${index+1}</b><strong>${esc(item)}</strong><span>${index===AXES[axis].length-1&&axis==="procedure"?"Final authority at the live event":"Apply only within its stated scope"}</span></li>`).join("");document.querySelectorAll("[data-axis]").forEach(button=>button.classList.toggle("active",button.dataset.axis===axis))}
function renderSourceOptions(){els.sourceSelect.innerHTML=SOURCES.filter(source=>source.status!=="superseded").map(source=>{const label=source.authority==="official"?"Official":source.authority==="judge_guidance"?"Judge guidance":"Community";return`<option value="${source.source_id}">${label} · ${esc(source.title)} (${source.version}, ${source.locale})</option>`}).join("");renderSourcePreview()}
function renderSourcePreview(){const source=SOURCES.find(item=>item.source_id===els.sourceSelect.value)||SOURCES[0];els.sourcePreview.innerHTML=`<strong>${esc(source.title)}</strong> · ${esc(source.document_class.replaceAll("_"," "))} · ${esc(source.locale)} / ${esc(source.region)} · ${source.live?"check live before use":"dated source"}${source.authority!=="official"?" · supporting only":""}`}
function renderEngineOptions(){els.engineSelect.innerHTML=ENGINE_CHECKS.map(item=>`<option value="${esc(item.check.check_id)}">${esc(item.check.outcome)} · ${esc(item.check.check_kind)} · ${esc(item.check.component.name)}</option>`).join("")}
// The check is shown through the shared read-only viewer rather than a local
// renderer: the outcome, its coverage limits, and the authority triple must
// read the same way in every system that displays one.
function renderEngineCheck(){const attached=consultation?.engine_checks||[],latest=attached[attached.length-1];els.engineCount.textContent=`${attached.length} attached`;if(!latest){els.engineView.replaceChildren();return}globalThis.RC_ENGINE_CHECK_VIEW.mount(els.engineView,latest)}
function pendingStage(){if(!consultation)return"question";if(!consultation.facts.length)return"context";if(!consultation.sources.length)return"source";if(consultation.status!=="final")return"answer";return"complete"}
function setStatus(stage){const map={question:["1","Define the question","Start with the interaction and its rules context."],context:["2","Establish facts and assumptions","At least one confirmed fact is required."],source:["3","Attach the rule basis","Use an exact locator and current official source."],answer:["4","Analyze and calibrate","Finalize the answer, confidence, and escalation."],complete:["✓","Consultation finalized","Export the record or start another question."]};const [n,title,detail]=map[stage];els.status.querySelector("span").textContent=n;els.status.querySelector("strong").textContent=title;els.status.querySelector("p").textContent=detail}
function renderRecord(){if(!consultation){els.record.classList.remove("has-items");els.recordEmpty.hidden=false;els.recordCount.textContent="0 items";els.record.innerHTML="";return}const groups=[];if(consultation.facts.length)groups.push(["Facts",consultation.facts.map(item=>`<div class="record-item"><strong>${esc(item.text)}</strong><span>${esc(item.origin.replaceAll("_"," "))}</span></div>`).join("")]);if(consultation.assumptions.length)groups.push(["Assumptions",consultation.assumptions.map(item=>`<div class="record-item"><strong>${esc(item.text)}</strong><span>${item.material?"material":"non-material"}</span></div>`).join("")]);if(consultation.sources.length)groups.push(["Sources",consultation.sources.map(item=>{const source=SOURCES.find(s=>s.source_id===item.source_id);return`<div class="record-item"><strong>${esc(source?.title||item.source_id)}</strong><p>${esc(item.locator)}</p><span>${esc(source?.authority||"unknown")}</span></div>`}).join("")]);if(consultation.engine_checks.length)groups.push(["Engine checks",consultation.engine_checks.map(item=>`<div class="record-item"><strong>${esc(item.outcome)} · ${esc(item.check_kind)}</strong><p>${esc(item.coverage.id)} · complete game: ${item.coverage.complete_game?"yes":"no"}</p><span>${esc(item.authority.official_status)} · consistency check only</span></div>`).join("")]);const count=consultation.facts.length+consultation.assumptions.length+consultation.sources.length+consultation.engine_checks.length;els.record.innerHTML=groups.map(([title,body])=>`<section class="record-group"><h3>${title}</h3>${body}</section>`).join("");els.record.classList.toggle("has-items",count>0);els.recordEmpty.hidden=count>0;els.recordCount.textContent=`${count} item${count===1?"":"s"}`}
function renderResult(){const answer=consultation?.answer;els.result.hidden=!answer;if(!answer)return;$("#result-confidence").textContent=`${answer.confidence} confidence${answer.conditional?" · conditional":""}`;$("#result-conclusion").textContent=answer.conclusion;$("#result-steps").innerHTML=answer.analysis_steps.map(step=>`<li>${esc(step)}</li>`).join("");$("#result-escalation").textContent=answer.escalation_required?`Escalate to ${answer.escalation_target.replaceAll("_"," ")}: ${answer.escalation_reason}`:"No escalation required on the supplied facts."}
function render(){const stage=pendingStage(),draft=consultation?.status==="draft";locked(els.questionForm,Boolean(consultation));locked($("#context-content"),!draft);locked(els.sourceForm,!draft);locked(els.engineForm,!draft);locked(els.answerForm,!draft||!consultation?.facts.length||!consultation?.sources.length);els.copyBrief.disabled=!draft||!consultation?.facts.length;els.export.disabled=!consultation;els.reset.disabled=!consultation;$("#question-status").textContent=consultation?"Complete":"Required";$("#context-status").textContent=!consultation?"Locked":consultation.facts.length?`${consultation.facts.length} facts`:"Required";$("#source-status").textContent=!consultation?"Locked":consultation.sources.length?`${consultation.sources.length} attached`:"Required";$("#answer-status").textContent=!consultation?"Locked":consultation.status==="final"?"Final":"Ready";$("#question-panel").open=!consultation;$("#context-panel").open=stage==="context";$("#source-panel").open=stage==="source";$("#answer-panel").open=stage==="answer";setStatus(stage);renderRecord();renderEngineCheck();renderResult()}
document.querySelectorAll("[data-axis]").forEach(button=>button.addEventListener("click",()=>renderLadder(button.dataset.axis)));
els.sourceSelect.addEventListener("change",renderSourcePreview);
els.questionForm.addEventListener("submit",event=>{event.preventDefault();const v=values(event.currentTarget),required=[v.createdBy,v.question,v.format,v.ruleset].map(item=>item.trim());if(required.some(item=>!item)){toast("Question, format, ruleset, and operator cannot be blank.");return}consultation={...CONSTANTS,consultation_id:id(),created_at:now(),created_by:required[0],status:"draft",question_type:v.questionType,question:required[1],format:required[2],ruleset_as_of:required[3],facts:[],assumptions:[],sources:[],engine_checks:[],answer:null};render();toast("Draft consultation created. No ruling has been asserted.")});
els.factForm.addEventListener("submit",event=>{event.preventDefault();const v=values(event.currentTarget),text=v.text.trim();if(!text){toast("A confirmed fact cannot be blank.");return}consultation.facts.push({text,origin:v.origin});event.currentTarget.elements.text.value="";render();toast("Confirmed fact added.")});
els.assumptionForm.addEventListener("submit",event=>{event.preventDefault();const v=values(event.currentTarget),text=v.text.trim();if(!text){toast("An assumption cannot be blank.");return}consultation.assumptions.push({text,material:v.material==="on"});event.currentTarget.reset();render();toast("Assumption separated from confirmed facts.")});
els.sourceForm.addEventListener("submit",event=>{event.preventDefault();const v=values(event.currentTarget),locator=v.locator.trim();if(!locator){toast("Use an exact rule, section, heading, or card locator.");return}if(consultation.sources.some(item=>item.source_id===v.sourceId&&item.locator===locator)){toast("That source and locator are already attached.");return}consultation.sources.push({source_id:v.sourceId,locator,accessed_at:now()});event.currentTarget.elements.locator.value="";render();toast("Source locator attached.")});
els.engineForm.addEventListener("submit",event=>{event.preventDefault();const fixture=ENGINE_CHECKS.find(item=>item.check.check_id===values(event.currentTarget).checkId);if(!fixture){toast("Select a check to attach.");return}if(consultation.engine_checks.some(item=>item.check_id===fixture.check.check_id)){toast("That check is already attached.");return}consultation.engine_checks.push(fixture.check);render();toast(fixture.check.outcome==="supported"?"Consistency check attached. It does not raise source confidence.":"Consistency check attached. The engine did not confirm; the official source still decides.")});
els.answerForm.addEventListener("submit",event=>{event.preventDefault();const v=values(event.currentTarget),material=consultation.assumptions.some(item=>item.material),official=consultation.sources.some(item=>{const source=SOURCES.find(candidate=>candidate.source_id===item.source_id);return source?.authority==="official"&&source.status==="active"}),conclusion=v.conclusion.trim(),steps=v.steps.split("\n").map(line=>line.trim()).filter(Boolean),reason=v.confidenceReason.trim();if(!conclusion||!steps.length||!reason){toast("Conclusion, analysis steps, and confidence reason cannot be blank.");return}if(v.confidence==="High"&&material){toast("High confidence is blocked while a material assumption remains.");return}if(v.confidence==="High"&&!official){toast("High confidence requires an official source.");return}if(v.escalationTarget!=="none"&&!v.escalationReason.trim()){toast("Explain why escalation is required.");return}if(consultation.question_type==="source_conflict"&&v.confidence==="High"){toast("A source conflict cannot finalize at High confidence.");return}consultation.status="final";consultation.answer={conclusion,conditional:v.conditional==="on",analysis_steps:steps,confidence:v.confidence,confidence_reason:reason,escalation_required:v.escalationTarget!=="none",escalation_target:v.escalationTarget,escalation_reason:v.escalationReason.trim()};render();toast("Unofficial consultation finalized with no state effect.")});
els.copyBrief.addEventListener("click",async()=>{const brief=["Use the Riftbound rule-consult mode.",`Question type: ${consultation.question_type}`,`Question: ${consultation.question}`,`Format: ${consultation.format}`,`Ruleset as of: ${consultation.ruleset_as_of}`,"Facts:",...consultation.facts.map(item=>`- [${item.origin}] ${item.text}`),"Assumptions:",...(consultation.assumptions.length?consultation.assumptions.map(item=>`- [${item.material?"material":"non-material"}] ${item.text}`):["- none recorded"]),"Return the most likely answer, rule basis with exact locators, analysis steps, confidence and reason, and escalation. State that the result is unofficial and has no game-state effect.","If this is for a live event, format the result as a judge-prep handoff: neutral question, missing facts, competing readings, and official locators. Do not assign a penalty or claim a binding ruling."].join("\n");try{await navigator.clipboard.writeText(brief);toast("Research brief copied.")}catch{toast("Clipboard permission unavailable; copy the record manually.")}});
els.export.addEventListener("click",()=>{const blob=new Blob([`${JSON.stringify(consultation,null,2)}\n`],{type:"application/json"}),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=`rule-consult-${consultation.consultation_id.slice(0,8)}.json`;link.click();URL.revokeObjectURL(url);toast("Consultation JSON exported.")});
els.reset.addEventListener("click",()=>{if(!confirm("Reset this in-tab consultation? Export first if you need the record."))return;consultation=null;[els.questionForm,els.factForm,els.assumptionForm,els.sourceForm,els.answerForm].forEach(form=>form.reset());renderSourceOptions();renderEngineOptions();render();toast("Consultation reset.")});
renderLadder("mechanics");renderSourceOptions();renderEngineOptions();render();
})();
